### PR TITLE
Release 15.11.04.001.

### PR DESCRIPTION
**Pull request by KingofGamesYami**
This can't me automatically merged, idk how to merge...

### CODE REVIEW

**Comment by btelman96** [comment]
Successfully Merged. In cases like this, you will have to go in and tell it case by case what to do with each conflict. Make sure to view change log.

**Comment by KingofGamesYami** [comment]
Thanks.  I'm assuming that has to be done from Android Studio or Github Desktop / Command Line?  If there's a way to do that using the website, I'd like to learn about it.

**Comment by btelman96** [comment]
I am not sure about the website. I prefer Android Studio since that is what I have the most experience with. You should be able to find something.

**Comment by KingofGamesYami** [comment]
I prefer the website, since I don't have AS on my school laptop - which is what I have access to most of the time.  I'll look into it, but I don't think the website can do it - at least with this big of requests.  It can't even show the full list of changes.

**Pull request merged**
